import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { aWeekAgoISO } from "../src/services/utils";
import { RepoListItem } from "../components/RepoListItem";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Trending repositories on GitHub</h1>

        <p className={styles.description}>See stared *</p>

        <div className={styles.grid}>
          {data.items.map((repo) => (
            <RepoListItem
              id={repo.id}
              html_url={repo.html_url}
              name={repo.name}
              description={repo.description}
              className={styles.card}
              key={repo.id}
            />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    `https://api.github.com/search/repositories?q=created:%3E${aWeekAgoISO()}&sort=stars&order=desc`
  );
  const data = await res.json();
  console.log(aWeekAgoISO());
  return {
    props: { data },
  };
};
